M48
; DRILL file {KiCad 7.0.6-0} date 2023 November 06, Monday 17:07:06
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-06T17:07:06-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1201
%
G90
G05
T1
X4.2602Y-5.0484
X4.4878Y-5.0484
T2
X5.9114Y-1.7055
X6.2421Y-1.7055
T0
M30
