M48
; DRILL file {KiCad 7.0.6-0} date 2023 December 08, Friday 23:06:08
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-08T23:06:08-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1201
%
G90
G05
T1
X4.2602Y-5.0484
X4.4878Y-5.0484
T2
X6.022Y-1.7024
X6.3528Y-1.7024
T0
M30
